import type { Metadata } from 'next'
import { Calistoga, Rubik } from 'next/font/google'
import './globals.css'

const inter = Rubik({ subsets: ['latin'], variable: '--font-sans' })
const calistoga = Calistoga({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-bg1 ${inter.variable} ${calistoga.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
